version: "3.1"

services:
  jtb-db:
    image: mysql:8.0
    restart: always
    container_name: dev-jtb-db
    ports:
     - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'dev_jtb_db'
      MYSQL_USER: 'dev_jtb_db_user'
      MYSQL_PASSWORD: 'dev_jtb_db_password'
      MYSQL_ROOT_PASSWORD: 'root'